# Generated by Django 5.2.8 on 2025-11-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_planner', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Note',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'notes'},
        ),
    ]
