# Generated by Django 5.2.8 on 2025-11-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_planner', '0004_note_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='topic',
        ),
    ]
